name: attendance
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Saya sarankan memperbarui beberapa paket penting ke versi yang lebih stabil/baru
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0 # Dotted Border (Ditingkatkan)
  camera: ^0.11.0+2 
  geolocator: ^11.0.0 # Geolocation (Ditingkatkan)
  geocoding: ^3.0.0  # Geocoding
  intl: ^0.20.1 
  lottie: ^3.3.1 
  google_mlkit_face_detection: ^0.12.0 
  cloud_firestore: ^5.0.0 # Connect Cloud Firestore (Ditingkatkan)
  firebase_core: ^3.0.0 # Connect Flutter to Firebase (Ditingkatkan)
  firebase_auth: ^5.0.0 # Firebase Authentication (Ditingkatkan)
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # KOREKSI ASSET:
  # Hapus '- assets/raw/' jika folder itu kosong atau tidak ada. 
  # Jika memang ada, pastikan ada file di dalamnya. Saya asumsikan Anda ingin menghapusnya untuk menghilangkan error pubspec.
  assets:
    - assets/images/ # JALUR INI SUDAH BENAR
    - assets/raw/